module.exports = [
'<!-- ====================================================== //',
'// ZehnerGroup: Build Rad Shit                              //',
'//                                                          //',
'// At ZehnerGroup, we love helping people build rad shit.   //',
'// We use tools like: React, AngularJS, node.js, Django,    //',
'// Python, PHP, Laravel, Wordpress, Chef, Ansible,          //',
'// and Docker. These are just to name a few.                //',
'//                                                          //',
'// If you love to build rad shit as well, join us. We are   //',
'// always hiring.                                           //',
'//                                                          //',
'// Head on over to: https://www.zehnergroup.com/careers     //',
'//                                                          //',
'// ======================================================= -->',
'']